sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tQ8wuKSCYeVeUZyQoxe
    access-key-secret: jqs5t8YpqJHtNtwSmwHWvPBJvkvURX
    bucket-name: cremi