sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root123
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: L##
    access-key-secret: j##
    bucket-name: cremi
  redis:
    host: 120.46.213.13
    port: 6379
    password: "@Mvplab123"
    database: 0
  wechat:
    app-id: wx8f4797882#
    secret: c8715808e04fac2cb881f671#
    mchid: c8715808e04fac2cb881f#
    mchSerialNo: c8715808e04fac2c#
    privateKeyFilePath: c8715808e04fac2cb881f#
    apiV3Key: c8715808e04fac2cb881f671#
    weChatPayCertFilePath: c8715808e04fac2cb88#
    notifyUrl: c8715808e04fac2cb881f6#
    refundNotifyUrl: c871580##
  shop:
    address: 江苏省南京市江宁区将军大道29号
  baidu:
    ak: 7Nq0AliXQ0gzekjzBTfye#
